go modules, go 1.16, golangci-lint
newrelic/nri-oracledb pull request #67
Opened 2021-04-21 09:26 UTC by roobre

2021-04-21 10:22 UTC, roobre commented
Please keep in mind that this is an ambitious refactor, which involves changing the driver used to connect to oracle databases with a new one from the same authors. Ideally changes should not be breaking, but this _needs to be e2e tested_.

2021-04-21 10:24 UTC, roobre commented
Snyk errors are related to missing files in the `vendor/` folder, and should be ignored.

2021-05-05 13:55 UTC, roobre commented
I've manually ran integration tests against an Oracle database in RDS.

Compared with the previous release of the integration, this build produced the following output:

```diff
ubuntu@ip:~$ diff old.json new.json
4c4
<   "integration_version": "2.5.3",
---
>   "integration_version": "0.0.0",
30,39c30,39
<           "db.averageActiveSessions": 0.0578540666666667,
<           "db.backgroundCheckpointsPerSecond": 0.0166666666666667,
<           "db.backgroundCpuUsagePerSecond": 0.492851666666667,
<           "db.backgroundTimePerSecond": 0.0104233333333333,
<           "db.blockChangesPerSecond": 1.33333333333333,
<           "db.blockChangesPerTransaction": 20,
<           "db.blockChangesPerUserCall": 0.260869565217391,
<           "db.blockGetsPerSecond": 1.73333333333333,
<           "db.blockGetsPerTransaction": 26,
<           "db.blockGetsPerUserCall": 0.332298136645963,
---
>           "db.averageActiveSessions": 5.00666666666667e-05,
>           "db.backgroundCheckpointsPerSecond": 0,
>           "db.backgroundCpuUsagePerSecond": 0.559915,
>           "db.backgroundTimePerSecond": 0.00966696666666667,
>           "db.blockChangesPerSecond": 0,
>           "db.blockChangesPerTransaction": 0,
>           "db.blockChangesPerUserCall": 0.0869565217391304,
>           "db.blockGetsPerSecond": 0,
>           "db.blockGetsPerTransaction": 0,
>           "db.blockGetsPerUserCall": 0.0869565217391304,
44,48c44,48
<           "db.consistentReadGetsPerSecond": 73.6,
<           "db.consistentReadGetsPerTransaction": 1104,
<           "db.cpuTimeRatio": 65.5908947916079,
<           "db.cpuUsagePerSecond": 3.570335,
<           "db.cpuUsagePerTransaction": 214.2201,
---
>           "db.consistentReadGetsPerSecond": 1.2,
>           "db.consistentReadGetsPerTransaction": 18,
>           "db.cpuTimeRatio": 146.604527296937,
>           "db.cpuUsagePerSecond": 0.0577083333333333,
>           "db.cpuUsagePerTransaction": 3.4625,
55,57c55,57
<           "db.cursorCacheHitsPerAttempts": 73.8326848249027,
<           "db.databaseCpuTimePerSecond": 5.78540666666667,
<           "db.dbwrCheckpointsPerSecond": 0.0166666666666667,
---
>           "db.cursorCacheHitsPerAttempts": 83.0188679245283,
>           "db.databaseCpuTimePerSecond": 0.00500666666666667,
>           "db.dbwrCheckpointsPerSecond": 0,
60,61c60,61
<           "db.enqueueRequestsPerSecond": 15.2166666666667,
<           "db.enqueueRequestsPerTransaction": 913,
---
>           "db.enqueueRequestsPerSecond": 9.71666666666667,
>           "db.enqueueRequestsPerTransaction": 583,
66,68c66,68
<           "db.executionsPerSecond": 17.5333333333333,
<           "db.executionsPerTransaction": 263,
<           "db.executionsPerUserCall": 3.1583850931677,
---
>           "db.executionsPerSecond": 0.133333333333333,
>           "db.executionsPerTransaction": 2,
>           "db.executionsPerUserCall": 1.26086956521739,
73,76c73,76
<           "db.hardParseCountPerSecond": 0.0666666666666667,
<           "db.hardParseCountPerTransaction": 4,
<           "db.hostCpuUsagePerSecond": 5.33333333333333,
<           "db.hostCpuUtilization": 2.68366320026837,
---
>           "db.hardParseCountPerSecond": 0,
>           "db.hardParseCountPerTransaction": 0,
>           "db.hostCpuUsagePerSecond": 0.933333333333333,
>           "db.hostCpuUtilization": 0.469641060046964,
79,83c79,83
<           "db.libraryCacheHitRatio": 99.4140625,
<           "db.libraryCacheMissRatio": 0.730994152046784,
<           "db.logicalReadsPerSecond": 75.3333333333333,
<           "db.logicalReadsPerTransaction": 1130,
<           "db.logonsPerTransaction": 5,
---
>           "db.libraryCacheHitRatio": 100,
>           "db.libraryCacheMissRatio": 0,
>           "db.logicalReadsPerSecond": 1.2,
>           "db.logicalReadsPerTransaction": 18,
>           "db.logonsPerTransaction": 0,
86,88c86,88
<           "db.openCursorsPerSecond": 17.2,
<           "db.openCursorsPerTransaction": 1032,
<           "db.osLoad": 0,
---
>           "db.openCursorsPerSecond": 0.883333333333333,
>           "db.openCursorsPerTransaction": 53,
>           "db.osLoad": 0.349609375,
93,97c93,97
<           "db.recursiveCallsPerSecond": 155.583333333333,
<           "db.recursiveCallsPerTransaction": 9335,
<           "db.redoWritesPerSecond": 0.4,
<           "db.redoWritesPerTransaction": 6,
<           "db.responseTimePerTransaction": 333.7184,
---
>           "db.recursiveCallsPerSecond": 14.7333333333333,
>           "db.recursiveCallsPerTransaction": 884,
>           "db.redoWritesPerSecond": 0,
>           "db.redoWritesPerTransaction": 0,
>           "db.responseTimePerTransaction": 2.4594,
100c100
<           "db.rowsPerSort": 8.61776061776062,
---
>           "db.rowsPerSort": 2.95294117647059,
103,106c103,106
<           "db.sharedPoolFreePercentage": 24.5135545730591,
<           "db.softParseRatio": 99.6268656716418,
<           "db.sortsPerUserCall": 5.6304347826087,
<           "db.sqlServiceResponseTime": 0.034557150253702,
---
>           "db.sharedPoolFreePercentage": 24.4921264194307,
>           "db.softParseRatio": 100,
>           "db.sortsPerUserCall": 1.84782608695652,
>           "db.sqlServiceResponseTime": 0.00264451612903226,
108,117c108,117
<           "db.tableScansPerUserCall": 0.409937888198758,
<           "db.totalIndexScansPerSecond": 30.2666666666667,
<           "db.totalIndexScansPerTransaction": 1816,
<           "db.totalParseCountPerSecond": 17.2,
<           "db.totalParseCountPerTransaction": 1032,
<           "db.totalTableScansPerSecond": 2.26666666666667,
<           "db.totalTableScansPerTransaction": 34,
<           "db.userCallsPerSecond": 5.13333333333333,
<           "db.userCallsPerTransaction": 77,
<           "db.userCallsRatio": 3.33436885161023,
---
>           "db.tableScansPerUserCall": 0.369565217391304,
>           "db.totalIndexScansPerSecond": 1.5,
>           "db.totalIndexScansPerTransaction": 90,
>           "db.totalParseCountPerSecond": 0.883333333333333,
>           "db.totalParseCountPerTransaction": 53,
>           "db.totalTableScansPerSecond": 0.2,
>           "db.totalTableScansPerTransaction": 3,
>           "db.userCallsPerSecond": 0.533333333333333,
>           "db.userCallsPerTransaction": 8,
>           "db.userCallsRatio": 4.94623655913978,
125c125
<           "db.waitTimeRatio": 35.80812445463,
---
>           "db.waitTimeRatio": 0,
129c129
<           "disk.logicalReadsPerUserCall": 14.2950310559006,
---
>           "disk.logicalReadsPerUserCall": 6.02173913043478,
132,138c132,138
<           "disk.physicalReadBytesPerSecond": 285815.466666667,
<           "disk.physicalReadIoRequestsPerSecond": 16.4666666666667,
<           "disk.physicalReadsPerSecond": 0.333333333333333,
<           "disk.physicalWriteBytesPerSecond": 24686.9333333333,
<           "disk.physicalWriteIoRequestsPerSecond": 0.25,
<           "disk.physicalWriteTotalIoRequestsPerSecond": 2.3,
<           "disk.physicalWritesPerSecond": 0.0833333333333333,
---
>           "disk.physicalReadBytesPerSecond": 58436.2666666667,
>           "disk.physicalReadIoRequestsPerSecond": 3.56666666666667,
>           "disk.physicalReadsPerSecond": 0,
>           "disk.physicalWriteBytesPerSecond": 14779.7333333333,
>           "disk.physicalWriteIoRequestsPerSecond": 0,
>           "disk.physicalWriteTotalIoRequestsPerSecond": 0.95,
>           "disk.physicalWritesPerSecond": 0,
155,157c155,157
<           "memory.pgaAllocatedInBytes": 336859136,
<           "memory.pgaFreeableInBytes": 39190528,
<           "memory.pgaInUseInBytes": 274119680,
---
>           "memory.pgaAllocatedInBytes": 336924672,
>           "memory.pgaFreeableInBytes": 35848192,
>           "memory.pgaInUseInBytes": 277569536,
160,165c160,165
<           "memory.redoGeneratedBytesPerSecond": 289.6,
<           "memory.redoGeneratedBytesPerTransaction": 4344,
<           "memory.sortsRatio": 100,
<           "network.ioMegabytesPerSecond": 0.3,
<           "net [...]

2021-05-06 08:03 UTC, davidbrota requested changes
Remember to replace validate with golangci-lint here
https://github.com/newrelic/nri-oracledb/blob/master/.github/workflows/prerelease.yml#L64
otherwise the CI pipeline won't start

thanks for the testing!

2021-05-06 08:03 UTC, davidbrota commented on build/Dockerfile
> +ARG GH_VERSION='1.6.0'
```suggestion
ARG GH_VERSION='1.6.2'
```

2021-05-06 11:49 UTC, roobre commented
> Remember to replace validate with golangci-lint here

Done, great catch @davidbrota!

2021-05-12 10:14 UTC, davidbrota approved these changes

2021-05-12 12:43 UTC, merged